global using Microsoft.Data.SqlClient;
global using Microsoft.EntityFrameworkCore;
global using System.ComponentModel.DataAnnotations;
global using System.ComponentModel.DataAnnotations.Schema;
global using MKKDotNetCore.ApiWithNLayer.Models;
global using MKKDotNetCore.ApiWithNLayer.Services;
global using MKKDotNetCore.ApiWithNLayer.Db;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Mvc;